### ISSUE TITLE
"../" vs "./"

### ISSUE THREAD

**Issue by OlenaShcherbakova** [HedvigS/R_grambank_cookbook#1]
For me, the paths as they are currently provided cause errors. Everything works as expected when I changed the beginning of the path from ".:/" to "./".

https://github.com/HedvigS/R_grambank_cookbook/blob/d66385b3f71056e73bd62c571a39482105864dfb/example_scripts/binarise.R#L27

**Comment by HedvigS** [comment]
@OlenaShcherbakova Thanks. 
The idea is that you are inside the folder called "example scripts". Maybe I should have made that clearer. Can you use that as your working dir instead?

**Comment by HedvigS** [comment]
I've added a commented line now in the scripts themselves that you should have  `R_grambank_cookbook/example_scripts` as working dir.

**Comment by HedvigS** [comment]
I updated the [readme](https://github.com/HedvigS/R_grambank_cookbook/blob/main/README.md#structure-of-content) too.

**Comment by OlenaShcherbakova** [comment]
Thanks, that's helpful!
And within that directory everything works as expected :)

**Comment by HedvigS** [comment]
related to https://github.com/dlce-eva/papers/pull/7
