### ISSUE TITLE
consistency suggestion

### ISSUE THREAD

**Issue by OlenaShcherbakova** [HedvigS/R_grambank_cookbook#2]
Here the object is labelled as "grambank_cldf_object", but in other scripts it is "grambank_cldf_obj". The commented out examples could be also "grambank_cldf_obj" for consistency with other scripts, but this is a minor thing.

https://github.com/HedvigS/R_grambank_cookbook/blob/d66385b3f71056e73bd62c571a39482105864dfb/functions/make_theo_scores.R#L14

**Comment by HedvigS** [comment]
Sure thing!

**Comment by HedvigS** [comment]
relates to https://github.com/dlce-eva/papers/pull/7
